### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xofbd** [xofbd/pastebin#1]
We need to decide on the license we are going to use

**Comment by xofbd** [comment]
One suggestion is to check out what licences other Python packages uses. I see a side project that uses the GitHub web API and crawls through a list of Python package repo and see what licenses they have. Either way, you should spend some time knowing a little about software licenses.

**Comment by i02132002** [comment]
Based on a quick search, it seems that a permissive license is a good fit for our purposes if we don't necessarily want to make money from it, but we want more people to use our software and build on it in the future. I suggest something like a 3-clause BSD license. It grants rights to use, distribute, modify and even relicense our software, plus a liability disclaimer so that if someone causes harm using our software, we're not liable. I think a license that forbids proprietization and relicensing (like GPLv3) is going to discourage use of our software. For my research, I'm using a python library called trackpy, which is used to track particle positions in an image. There they use the 3-clause BSD license as well.

**Comment by xofbd** [comment]
@i02132002 Thanks!
@shakibaRafiee Let us know what you think and have come up with?

**Comment by shakibaRafiee** [comment]
For this project, I was thinking we would probably want to go with one of these 4 most common open-source licenses: GPL, MIT, Apache, and BSD. I get Franklin's point that a permissive license ( MIT, Apache, and BSD) would be good enough for our project. But I also noticed that Pastebin is using the GPL license which is copy-left. I still don't fully grasp these licenses. Just to be safe, I would probably go with the GLP, in the case we wanted to modify some of the original Pastebin material.

**Comment by shakibaRafiee** [comment]
@i02132002  Yes, you are correct the licenses does not apply to the data on the site. I was thinking in the improbable case we end up also playing around with their source code, we might want to use the same license, but you are right, that is not very probable.

**Comment by xofbd** [comment]
I think @i02132002 is correct. In short GPL says one can do whatever they want except that any derivative work must _still_ be GPL.

**Comment by xofbd** [comment]
I agree we should go with something that is permissive, i.e., allow for others to do whatever they want. That'll be either MIT, Apache, or BSD.

Any strong opinions here? I don't

**Comment by shakibaRafiee** [comment]
Not really, most packages that I have seen have used the MIT License, but honestly, I don't know these licenses well enough to have a strong opinion :)

**Comment by xofbd** [comment]
I don't know too much about the differences between MIT, Apache, and BSD either. I think MIT is short and sweet.

**Comment by i02132002** [comment]
Ok, let's go with the MIT license then. They have a template here: https://opensource.org/licenses/MIT
What do we put for the copyright holder?

**Comment by xofbd** [comment]
Our names in alphabetical order.

**Comment by xofbd** [comment]
Let's go with the MIT license.
@shakibaRafiee Can you open a pull request with the license and make me and @i02132002 reviewers?

**Comment by shakibaRafiee** [comment]
on it.

**Comment by xofbd** [comment]
resolved by #9
